### ISSUE TITLE
[Refactor] refactoring test code

### ISSUE THREAD

**Issue by heechul90** [woorinpang/user-service#67]
# Description
- 지금까지 개발하면서 테스트 케이스를 작성하지 않았다.
- 테스트코드는 필수적으로 작성하자!
- 지금까지 개발한 기능의 테스트를 다 개발하고 다음 개발을 하자

# Todo
- [x] user repositoy test case
- [x] user service test case
- [x] user controller test case
